-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN "llmTokenBudget" INTEGER NOT NULL DEFAULT 10000;
ALTER TABLE "Tenant" ADD COLUMN "llmTokenSpent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN "killSwitchOn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN "killSwitchReason" TEXT;
