export const WEB_API_PROXY_PREFIXES = [
  '/auth',
  '/health',
  '/docs',
  '/tenants',
  '/imports',
  '/mock-source',
  '/cases',
  '/drafts',
  '/outbox',
  '/replies',
  '/tasks',
  '/events',
  '/suppression',
] as const
